#!/usr/bin/env bash

# +-----+
# | lsd |
# +-----+

alias l='lsd -1'
alias ll='lsd -l'
alias la='lsd -a1'
alias lla='lsd -al'
alias lt='lsd --tree'
alias lt1='lsd --tree --depth 1'
alias lt2='lsd --tree --depth 2'
alias lt3='lsd --tree --depth 3'
alias lt4='lsd --tree --depth 4'
alias lt5='lsd --tree --depth 5'

# +-----+
# | zsh |
# +-----+

# Every directory visited will populate the directory stack
# The alias will display the directories on the stack prefixed with a number
alias d='dirs -v'

# Create aliases 1 to 9, which, when used, will jump directly to the corresponding directory on your stack
for index ({1..9}) alias "$index"="cd +${index} > /dev/null"; unset index

# +---------+
# | scripts |
# +---------+

# Run dotfiles update
alias updot='$REPOS_PERSONAL/.dotfiles/deploy-config-linux.sh'

# +---------+
# | general |
# +---------+

alias clr='clear'
