#!/usr/bin/env bash

# +-----+
# | lsd |
# +-----+

alias l='lsd -1'
alias ll='lsd -l'
alias la='lsd -a1'
alias lla='lsd -al'
alias lt='lsd --tree'
alias lt1='lsd --tree --depth 1'
alias lt2='lsd --tree --depth 2'
alias lt3='lsd --tree --depth 3'
alias lt4='lsd --tree --depth 4'
alias lt5='lsd --tree --depth 5'

# +---------+
# | general |
# +---------+

alias clr='clear'
