#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# Source common environment variables
[ -f "$HOME/.env" ] && source "$HOME/.env"

# Editor
export EDITOR="nano"
export VISUAL="nano"

# ZSH
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"   # ZSH Home directory
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file
